security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: name
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                # "app_login" is the name of the route in the LoginController
                login_path: app_login
                check_path: app_login
                default_target_path: home
                enable_csrf: true
                #hide_user_not_found: true (this setting is in the docs but causes exception)
                username_parameter: _johndayun_
                password_parameter: _johndaypw_
                csrf_parameter: _johndaytok_

            # this is not compatible with our auto logout behaviour
            #remember_me:
            #    secret:   '%kernel.secret%' # required
            #    lifetime: 604800            # 1 week in seconds
            #    name: _johndayrm_

            login_throttling:
                max_attempts: 3
                interval: '1 minute'        # default

            logout:
                path: /logout               # url is /_logout_main
                target: app_login

    role_hierarchy:
        ROLE_ADMIN:     ROLE_USER

    #if our custom security voter says no, that it means it
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    # Simple access control > Note: Only the *first* access control that matches will be used
    # we require log in per session
    access_control:
        - { path: ^/login|public, roles: PUBLIC_ACCESS, requires_channel: '%env(REQUIRED_SCHEME)%' }
        - { path: ^/admin/*, roles: [ROLE_ADMIN, IS_AUTHENTICATED_FULLY, 'SAME_SESSION'], requires_channel: '%env(REQUIRED_SCHEME)%' }
        - { path: ^/*, roles: [IS_AUTHENTICATED_FULLY, 'SAME_SESSION'], requires_channel: '%env(REQUIRED_SCHEME)%'}

when@test:
    security:
        password_hashers:
            # ONLY FOR TESTS
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
